### ISSUE TITLE
Spot lights projecting light through objects

### ISSUE THREAD

**Issue by fabulastudios** [Cyanilux/URP_ShaderGraphCustomLighting#11]
Hey

I have found a weird problem with the spotlights. They seem to ignore distance in some instances the light shines through objects. Im using Unity 2021.3 LTS

 
![image](https://user-images.githubusercontent.com/57254337/199193840-4c5a2f32-bc9b-4de0-82b3-481f39fbb180.png)

![image](https://user-images.githubusercontent.com/57254337/199193976-2b54e29c-942a-4027-a818-4492e9a1f6f0.png)

**Comment by fabulastudios** [comment]
I have found that if I change the spotlight bands parameter for AdditionalLightsToon (Custom function) to 1, it does not happen

**Comment by fabulastudios** [comment]
I would think the problem lies in "float ToonAttenuation()".

**Comment by Cyanilux** [comment]
Thanks for reporting this issue! should now be fixed in main branch~
