### ISSUE TITLE
Does not work / Examples are all pink

### ISSUE THREAD

**Issue by Berlin-Koeln** [Cyanilux/URP_ShaderGraphCustomLighting#20]
Is there something to configure befor use? 
I imported it form asset store and all the examples were pink. Then i imported it from git with the same result. 
Is there something to setup befor i can use this shader? 
Is there a manual?

**Comment by Cyanilux** [comment]
This requires the [Universal Render Pipeline](https://docs.unity3d.com/Packages/com.unity.render-pipelines.universal@17.0/manual/index.html), so won't work for projects using the Built-in RP or HDRP. The main branch also requires Unity 2021.2 onwards, but there's another branch for older versions.

Just FYI, If you try to switch pipeline it may break a lot of other things. Always back-up the project before attempting that. Or look for a different asset/tutorial intended for whichever pipeline you're using. e.g. can do custom lighting in surface shaders for Built-in.

Also not sure what you mean by "imported it from asset store". I don't have anything on there. Perhaps you meant package manager or are talking about a different asset.
