### ISSUE TITLE
MainLightShadows Does not work in Subgraph

### ISSUE THREAD

**Issue by Sooly890** [Cyanilux/URP_ShaderGraphCustomLighting#22]
In Unlit Graph:
![image](https://github.com/Cyanilux/URP_ShaderGraphCustomLighting/assets/130508235/d44412d8-4343-45f2-b80d-b67bae88df3b)
![image](https://github.com/Cyanilux/URP_ShaderGraphCustomLighting/assets/130508235/32f4fa00-8fc7-41f1-9d88-e4d2fec94cca)

In Subgraph Connected to Unlit Graph
![image](https://github.com/Cyanilux/URP_ShaderGraphCustomLighting/assets/130508235/1d742aea-35f2-4030-8b8d-2219aaf3c38c)
![image](https://github.com/Cyanilux/URP_ShaderGraphCustomLighting/assets/130508235/79998736-c02d-4435-987b-25fda9a4632d)
(ignore the parameters, they are not attached to anything)
![image](https://github.com/Cyanilux/URP_ShaderGraphCustomLighting/assets/130508235/11f23546-2b00-4bdc-b564-7af150673085)

What's going on here?

**Comment by Cyanilux** [comment]
Heya, this is bit of a limitation of ShaderGraph - it doesn't collect the keywords (defined in the Blackboard) from nested subgraphs. You can copy to / recreate them in the main graph and it should work though.

- Enum Keyword, Global Multi-Compile `_MAIN_LIGHT`, with entries :
   - `SHADOWS`
   - `SHADOWS_CASCADE`
   - `SHADOWS_SCREEN`
- Boolean Keyword, Global Multi-Compile `_SHADOWS_SOFT`

**Comment by Sooly890** [comment]
@Cyanilux  thanks for the reply, is there really no way to get around this (except redefining the keywords)? I'll use this for now ~~but it would be nice to have a nice packaged CustomLight subgraph that can be drag and dropped~~
I read your comment wrong. This will work sufficiently for me
