### ISSUE TITLE
Is this solution maintained?

### ISSUE THREAD

**Issue by ciprianbiris** [Cyanilux/URP_ShaderGraphCustomLighting#24]
Hi. I'd like to know if you plan to maintain this with future versions of Unity?
I can see that the last commit is more than 1 year old..

Kind regards,

**Comment by Cyanilux** [comment]
Yes... there just hasn't been any changes in the past year that have caused need for an update afaik.

I can't make any promises beyond Unity 6, as with Shader Graph 2 and the plan to unify the pipelines everything may break / work differently. But that's some years away.
