### ISSUE TITLE
Depth and Normal Bias don't seem to affect the result

### ISSUE THREAD

**Issue by tyunderwood** [Cyanilux/URP_ShaderGraphCustomLighting#3]
![image](https://user-images.githubusercontent.com/2991628/109431205-29f91600-79ba-11eb-862f-504b773cfb9f.png)
Artifacting seems to not be resolvable by tweaking depth and normal bias. Am I missing something or is this not implemented? 

Thanks

**Comment by Cyanilux** [comment]
As in the depth/normal biases aren't affecting the result at all? The biases aren't implemented in my code as they should be handled in the ShadowCaster pass. Shader Graph already handles it automatically. If you're writing shader code though, you'll want to make sure that pass uses the [ApplyShadowBias](https://github.com/Unity-Technologies/Graphics/blob/cf1be4d0963869207415ac54352f26ebc797043e/com.unity.render-pipelines.universal/ShaderLibrary/Shadows.hlsl#L432) function from Shadows.hlsl. (see [ShadowCastPass.hlsl](https://github.com/Unity-Technologies/Graphics/blob/master/com.unity.render-pipelines.universal/Shaders/ShadowCasterPass.hlsl) for example)

I think this might just be how shadows look in URP so not sure I can help. Can try increasing the shadow quality or cascades settings. Maybe smoothing the terrain out a bit. Textures, diffuse (e.g. N dot L) and ambient lighting can also hide the artifacts a bit.
