### ISSUE TITLE
Question about MainLightShadows

### ISSUE THREAD

**Issue by jackrbbit** [Cyanilux/URP_ShaderGraphCustomLighting#4]
Really cool package, I can't thank you enough for this ! I was wondering and fiddling with it and is there a way to actually remove the "self-shadowing" from the MainLightShadows. I've been trying for a good while now to get access to the unity shadow texture and the fact is while I'm compositing my lighting I've got issue that comes from trying to remove the ugly self shadowing that I'm getting with the node. It might not be possible maybe the actual shadow looks like this, but since I'm compositing my own self shadowing with the inverse DOT it kinda conflict with it. The projected shadow are so smooth and nice compared to what the self shadows are. :/ I'm a noob at HLSL could've probably figured it out in shaderlab, but now I'm a bit lost. Thanks in advance for your time! 

![debug mainlight shadow](https://user-images.githubusercontent.com/6878792/114600102-f91b2a80-9c61-11eb-93d6-cbfb8cdfafcf.jpg)

**Comment by jackrbbit** [comment]
I guess it's just not possible since the mesh is also casting shadow on itself, but weirdly enough projected shadow are really nice and smooth with the self-shadowing provided by unity is just kinda bad and vertex based. I'll try out another approach to actually mask it out via my Lighting DOT. Sorry for the dumb question good sir ! Also you should put a link up for donation because this is just a golden package ! :) 

![image](https://user-images.githubusercontent.com/6878792/114604936-89a83980-9c67-11eb-9e66-9bf130beff45.png)
it's the best it can get I guess ;)

**Comment by Cyanilux** [comment]
Yeah, I don't think there's a way to avoid the self shadowing (without removing shadow casting from the object completely but that's probably not what you want). The N dot L is usually combined with the shadows to hide it though. The vertex-y look might also look smoother if the shadow bias settings are adjusted on the URP asset.

**Comment by jackrbbit** [comment]
Yes thanks a lot! I've figured as well, I was about to kinda go the hard way around with this ,but ended up using my N dot L as a mask, smoothstep it to refine and get as much of it out as possible without feeling a skewed lighting is the way to go here. I was about to dive into custom render passes and try to figure out how to get some global shadow map, but the same issue would've occured anyway. Thx again and really sorry to have bothered you with that ! :) It really amazing what can be done with your custom nodes.

**Comment by jackrbbit** [comment]
![SSS_CompAnd math polish](https://user-images.githubusercontent.com/6878792/114619273-58843500-9c78-11eb-8ee3-30ceb5a99b8e.gif)
I mean I added a lot on top already with SSS and normal map lighting ;) And I'm serious about if you ever create a place to receive donation I'm clearly gonna donate, cause this is just a life saver for any tech artist making a switch from standard to Scriptable pipeline and you sir deserves a medal ! :) Cheers :)
