### ISSUE TITLE
Getting shader include errors with URP 13.1.8

### ISSUE THREAD

**Issue by MrFJ** [Cyanilux/URP_ShaderGraphCustomLighting#8]
Hey I'm getting these two errors:
`Shader error in 'Shader Graphs/ShadowReceiver': Couldn't open include file 'Packages/com.cyanilux.shadergraph-customlighting/CustomLighting.hlsl'. at line 210`
`Shader error in 'Shader Graphs/ShadowReceiver': Couldn't open include file 'Packages/com.cyanilux.shadergraph-customlighting/CustomLighting.hlsl'. at line 877`

Any ideas?

**Comment by Cyanilux** [comment]
Try restarting Unity. If that doesn't work, maybe remove the package and reinstall it.
